sudo: required
dist: bionic
language: ruby
rvm:
  - 3.0.6
branches:
  only:
  - master
script:
  - RAILS_ENV=test ./run_tests
before_install:
  - gem install bundler -v 2.4.3
  - gem build cloud_storage_interface.gemspec